In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sympy import *
from sklearn.linear_model import LinearRegression
init_printing(use_unicode=True)

In [2]:
x_1, x_2, x_3, y_1, y_2, y_3, theta_1, theta_2, theta_3 = symbols('x^{(1)} x^{(2)} x^{(3}} y^{(1)} y^{(2)} y^{(3)} \Theta^{(1)} \Theta^{(2)} \Theta^{(3)}')

In [3]:
def normal(X, y):
    XT = X.T
    XTX = XT*X
    XTX_inv = XTX**-1
    XTy = XT*y
    return XTX_inv * XTy

In [4]:
def update_normal(X_full, y_full, X_obscured, y_obscured, original_n):
    n,d = X.shape
    #X_list, y_list = X_full.tolist(), y_full.tolist()
    theta_full = []
    lefts = []
    original_X, original_y = X_full[:original_n,:], y_full[:original_n,:]
    original_X_obs, original_y_obs = X_obscured[:original_n,:], y_obscured[:original_n,:]
    
    lm = LinearRegression(fit_intercept=False)
    
    lm.fit(original_X, original_y)
    theta_full.append(lm.coef_[0])
    for i in range(original_n+1, n+1):
        try:
            updated_X, updated_y = X_full[:i,:], y_full[:i,:]
            updated_X_obs, updated_y_obs = X_obscured[:i,:], y_obscured[:i,:]

            lm.fit(updated_X, updated_y)
            theta_full.append(lm.coef_[0])

            left = normal(updated_X_obs, updated_y_obs)
            lefts.append(left)
        except:
            continue
    sys_eqs = []
    diff = len(theta_full) - len(lefts)
    print(diff)
    for i in range(len(lefts)):
        for j in range(d):
            eq = lefts[i][j] - theta_full[i+diff][j]
            sys_eqs.append(eq)
    return theta_full, lefts, sys_eqs
    #return theta_full, lefts
    #return solvers.solve(sys_eqs)

In [5]:
X = Matrix([[3,4],[1,2],[0,3]])
y = Matrix([5,3,4])
X_obs = Matrix([[x_1,x_2],[1,2],[0,3]])
y_obs = Matrix([y_1,3,4])

In [6]:
a = update_normal(X,y,X_obs,y_obs,1)

1


In [7]:
a[0]

[array([0.6, 0.8]), array([-1.,  2.]), array([-0.10638298,  1.36170213])]

In [8]:
a[1]

⎡⎡                                                                            
⎢⎢       (x__{(1)}⋅x__{(2)} + 2)⋅(x__{(2)}⋅y__{(1)} + 6)         (x__{(1)}⋅y__
⎢⎢- ────────────────────────────────────────────────────────── + ─────────────
⎢⎢  ⎛        2    ⎞ ⎛        2    ⎞                          2                
⎢⎢  ⎝x__{(1)}  + 1⎠⋅⎝x__{(2)}  + 4⎠ - (x__{(1)}⋅x__{(2)} + 2)                 
⎢⎢                                                                            
⎢⎢                                                ⎛        2    ⎞             
⎢⎢                                                ⎝x__{(1)}  + 1⎠⋅(x__{(2)}⋅y_
⎢⎢                                       ─────────────────────────────────────
⎢⎢                                       ⎛        2    ⎞ ⎛        2    ⎞      
⎣⎣                                       ⎝x__{(1)}  + 1⎠⋅⎝x__{(2)}  + 4⎠ - (x_

           ⎛⎛        2    ⎞ ⎛        2    ⎞                                   
{(1)} + 3)⋅⎝⎝x__{(1)}  + 1⎠⋅⎝x__{(2)}  + 4⎠ - (-x__

In [9]:
solve(a[2], quick=True)

KeyboardInterrupt: 

In [80]:
X = Matrix([[3,4,5],[1,2,3],[9,3,1],[8,2,4]])
y = Matrix([6,4,-4,7])
X_obs = Matrix([[x_1,x_2,x_3],[1,2,3],[9,3,1],[8,2,4]])
y_obs = Matrix([y_1,4,-4,7])

In [81]:
a = update_normal(X,y,X_obs,y_obs,1)

2


In [82]:
a[0]

[array([0.36, 0.48, 0.6 ]),
 array([-0.66666667,  0.33333333,  1.33333333]),
 array([-0.75,  0.5 ,  1.25]),
 array([-0.04339623, -2.15471698,  2.90754717])]

In [85]:
solve(a[2], quick=True)

KeyboardInterrupt: 